repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: check-ast
      - id: check-merge-conflict
      - id: check-docstring-first

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML, types-click]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.14.0
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ['-r', '.', '-x', 'tests/']
        exclude: ^tests/

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check

  - repo: local
    hooks:
      - id: check-emojis
        name: Check for emojis in code
        entry: .venv/bin/python -c "import re, sys; emoji_pattern = re.compile(r'[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F1E0-\U0001F1FF\U00002600-\U000027BF\U0001F900-\U0001F9FF\U0001F018-\U0001F0F5\U0001F200-\U0001F2FF]'); files_with_emojis = [f for f in sys.argv[1:] if emoji_pattern.search(open(f, 'r', encoding='utf-8').read())]; [print(f'Emoji found in {f}') for f in files_with_emojis]; sys.exit(1 if files_with_emojis else 0)"
        language: system
        files: \.(py|md|txt|yml|yaml)$
        pass_filenames: true

      - id: ai-context-check
        name: AI Context Check
        entry: python scripts/check_ai_context.py
        language: system
        types: [python]
        pass_filenames: false
        description: Ensure AI Context Manager is properly configured

      - id: self-hosting-validation
        name: Self-Hosting Validation
        entry: python scripts/validate_self_hosting.py
        language: system
        types: [python]
        pass_filenames: false
        description: Validate self-hosting functionality
